// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// hs_alpha_gibbs_cpp
arma::mat hs_alpha_gibbs_cpp(const arma::vec& Y0_pre, const arma::mat& control_outcome_pre, const int iteration, const int burn, const bool verbose);
RcppExport SEXP _scspill_hs_alpha_gibbs_cpp(SEXP Y0_preSEXP, SEXP control_outcome_preSEXP, SEXP iterationSEXP, SEXP burnSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type Y0_pre(Y0_preSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type control_outcome_pre(control_outcome_preSEXP);
    Rcpp::traits::input_parameter< const int >::type iteration(iterationSEXP);
    Rcpp::traits::input_parameter< const int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(hs_alpha_gibbs_cpp(Y0_pre, control_outcome_pre, iteration, burn, verbose));
    return rcpp_result_gen;
END_RCPP
}
// sar_full_sampler_cpp_step2
Rcpp::List sar_full_sampler_cpp_step2(const arma::mat& Yc_pre, const arma::vec& alpha_hat_in, Rcpp::Nullable<Rcpp::NumericVector> Xc_pre_, int T0, int N, int K, int p, const arma::vec& w_in, const arma::mat& W, int iteration, int burn, double step_rho, double a0, double b0, bool verbose);
RcppExport SEXP _scspill_sar_full_sampler_cpp_step2(SEXP Yc_preSEXP, SEXP alpha_hat_inSEXP, SEXP Xc_pre_SEXP, SEXP T0SEXP, SEXP NSEXP, SEXP KSEXP, SEXP pSEXP, SEXP w_inSEXP, SEXP WSEXP, SEXP iterationSEXP, SEXP burnSEXP, SEXP step_rhoSEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Yc_pre(Yc_preSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha_hat_in(alpha_hat_inSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type Xc_pre_(Xc_pre_SEXP);
    Rcpp::traits::input_parameter< int >::type T0(T0SEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w_in(w_inSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< int >::type iteration(iterationSEXP);
    Rcpp::traits::input_parameter< int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< double >::type step_rho(step_rhoSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(sar_full_sampler_cpp_step2(Yc_pre, alpha_hat_in, Xc_pre_, T0, N, K, p, w_in, W, iteration, burn, step_rho, a0, b0, verbose));
    return rcpp_result_gen;
END_RCPP
}
// simulate_Yc_forward_cpp
arma::mat simulate_Yc_forward_cpp(int T0, const arma::mat& W_use, const arma::vec& w_use, const arma::vec& alpha_hat_scaled, double rho, double sigma2, const arma::cube& Xc_pre, const arma::vec& beta, const arma::mat& Eta, const arma::mat& Gamma);
RcppExport SEXP _scspill_simulate_Yc_forward_cpp(SEXP T0SEXP, SEXP W_useSEXP, SEXP w_useSEXP, SEXP alpha_hat_scaledSEXP, SEXP rhoSEXP, SEXP sigma2SEXP, SEXP Xc_preSEXP, SEXP betaSEXP, SEXP EtaSEXP, SEXP GammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type T0(T0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W_use(W_useSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w_use(w_useSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha_hat_scaled(alpha_hat_scaledSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type Xc_pre(Xc_preSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Eta(EtaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Gamma(GammaSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_Yc_forward_cpp(T0, W_use, w_use, alpha_hat_scaled, rho, sigma2, Xc_pre, beta, Eta, Gamma));
    return rcpp_result_gen;
END_RCPP
}
// scspill_one_step_cpp
Rcpp::List scspill_one_step_cpp(const arma::mat& Yc_data, const arma::mat& W_use, const arma::vec& w_use, const arma::vec& alpha_hat_scaled, int T0, int N, const arma::cube& Xc_pre, int K, int p, Rcpp::List state_in, double a0, double b0, double step_rho, double rho_lo, double rho_hi);
RcppExport SEXP _scspill_scspill_one_step_cpp(SEXP Yc_dataSEXP, SEXP W_useSEXP, SEXP w_useSEXP, SEXP alpha_hat_scaledSEXP, SEXP T0SEXP, SEXP NSEXP, SEXP Xc_preSEXP, SEXP KSEXP, SEXP pSEXP, SEXP state_inSEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP step_rhoSEXP, SEXP rho_loSEXP, SEXP rho_hiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Yc_data(Yc_dataSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W_use(W_useSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w_use(w_useSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha_hat_scaled(alpha_hat_scaledSEXP);
    Rcpp::traits::input_parameter< int >::type T0(T0SEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type Xc_pre(Xc_preSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type state_in(state_inSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type step_rho(step_rhoSEXP);
    Rcpp::traits::input_parameter< double >::type rho_lo(rho_loSEXP);
    Rcpp::traits::input_parameter< double >::type rho_hi(rho_hiSEXP);
    rcpp_result_gen = Rcpp::wrap(scspill_one_step_cpp(Yc_data, W_use, w_use, alpha_hat_scaled, T0, N, Xc_pre, K, p, state_in, a0, b0, step_rho, rho_lo, rho_hi));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_scspill_hs_alpha_gibbs_cpp", (DL_FUNC) &_scspill_hs_alpha_gibbs_cpp, 5},
    {"_scspill_sar_full_sampler_cpp_step2", (DL_FUNC) &_scspill_sar_full_sampler_cpp_step2, 15},
    {"_scspill_simulate_Yc_forward_cpp", (DL_FUNC) &_scspill_simulate_Yc_forward_cpp, 10},
    {"_scspill_scspill_one_step_cpp", (DL_FUNC) &_scspill_scspill_one_step_cpp, 15},
    {NULL, NULL, 0}
};

RcppExport void R_init_scspill(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
