---
title: "Sudan Split: Replication"
author: "scspill"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Sudan split}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  fig.width = 7,
  fig.height = 4,
  message = FALSE,
  warning = FALSE
)
```

```{r}
# library(scspill)
load("./data/sudan_secession_latest.rda")

panel_df <- sudan_secession_latest$panel
w_vec <- sudan_secession_latest$w
W_mat <- sudan_secession_latest$W
panel_df <- panel_df %>%
  mutate(
    treatment = ifelse((country == "Sudan") & (year >= 2011), 1, 0)
  )

```

```{r}
w <- as.matrix(w_vec[, 2])
W <- as.matrix(W_mat[, -1])

fit <- sc_spillover(
  data = panel_df,
  treated_unit = "Sudan",
  w = w,
  W = W,
  treatment_dummy = "treatment",
  y = colnames(panel_df)[11],
  X = colnames(panel_df)[4:10],
  p_factors = 1,
  M = 5000,
  burn = 2500,
  seed = 20251022,
  step_rho = 0.1,
  unit_col = "country",
  time_col = "year"
)

```

```{r fig3b}
plot(fit, time_col = "year")
plot(fit, type = "spill_top", top_n = 8, time_col = "year")
```

```{r fig4}
p <- diagnostics.scspill(
  fit,
  which_alpha = NULL,
  top_n_alpha = 6,
  which_beta = NULL,
  top_n_beta = 6
)
print(p)
```
