# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hs_alpha_gibbs_cpp <- function(Y0_pre, control_outcome_pre, iteration, burn, verbose = FALSE) {
    .Call(`_scspill_hs_alpha_gibbs_cpp`, Y0_pre, control_outcome_pre, iteration, burn, verbose)
}

sar_full_sampler_cpp_step2 <- function(Yc_pre, alpha_hat_in, Xc_pre_, T0, N, K, p, w_in, W, iteration, burn, step_rho = 0.01, a0 = 1.0, b0 = 1.0, verbose = FALSE) {
    .Call(`_scspill_sar_full_sampler_cpp_step2`, Yc_pre, alpha_hat_in, Xc_pre_, T0, N, K, p, w_in, W, iteration, burn, step_rho, a0, b0, verbose)
}

simulate_Yc_forward_cpp <- function(T0, W_use, w_use, alpha_hat_scaled, rho, sigma2, Xc_pre, beta, Eta, Gamma) {
    .Call(`_scspill_simulate_Yc_forward_cpp`, T0, W_use, w_use, alpha_hat_scaled, rho, sigma2, Xc_pre, beta, Eta, Gamma)
}

scspill_one_step_cpp <- function(Yc_data, W_use, w_use, alpha_hat_scaled, T0, N, Xc_pre, K, p, state_in, a0, b0, step_rho, rho_lo, rho_hi) {
    .Call(`_scspill_scspill_one_step_cpp`, Yc_data, W_use, w_use, alpha_hat_scaled, T0, N, Xc_pre, K, p, state_in, a0, b0, step_rho, rho_lo, rho_hi)
}

